import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/Splitties/refreshVersions
 */
public object Libs {
    public const val flatlaf: String = "com.formdev:flatlaf:_"

    public const val flatlaf_intellij_themes: String = "com.formdev:flatlaf-intellij-themes:_"

    public const val guava: String = "com.google.guava:guava:_"

    public const val assertk: String = "com.willowtreeapps.assertk:assertk:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val koin_core: String = "io.insert-koin:koin-core:_"

    public const val bcprov_jdk15on: String = "org.bouncycastle:bcprov-jdk15on:_"

    public const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib"

    public const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test"

    public const val json: String = "org.json:json:_"

    public const val asm: String = "org.ow2.asm:asm:_"

    public const val asm_commons: String = "org.ow2.asm:asm-commons:_"

    public const val asm_tree: String = "org.ow2.asm:asm-tree:_"

    public const val asm_util: String = "org.ow2.asm:asm-util:_"

    public const val pf4j: String = "org.pf4j:pf4j:_"

    public const val tinylog_api_kotlin: String = "org.tinylog:tinylog-api-kotlin:_"

    public const val tinylog_impl: String = "org.tinylog:tinylog-impl:_"
}
