public class class424 {
   public static String field3001;
   public static String field3002 = "";
   public static String field3003;
   public static String field3004 = "This world is full.";
   public static String field3005 = "Ok";
   public static String field3006;
   public static String field3007 = "Continue";
   public static String field3008;
   public static String field3009;
   public static String field3010 = "Trust this computer";
   public static String field3011;
   public static String field3012 = "Loading - please wait.";
   public static String field3013 = "Connection lost";
   public static String field3014 = "Please wait - attempting to reestablish";
   public static String field3015 = "Starting game engine...";
   public static String field3016 = "Prepared visibility map";
   public static String field3017;
   public static String field3018 = "Checking for updates - ";
   public static String field3019 = "Loaded update list";
   public static String field3020 = "Prepared sound engine";
   public static String field3021;
   public static String field3022 = "Loaded fonts";
   public static String field3023 = "Loading title screen - ";
   public static String field3024 = "Loaded title screen";
   public static String field3025 = "Loading config - ";
   public static String field3026;
   public static String field3027 = "Loading sprites - ";
   public static String field3028 = "Loaded sprites";
   public static String field3029 = "Loading textures - ";
   public static String field3030;
   public static String field3031 = "";
   public static String field3032;
   public static String field3033 = "Loaded wordpack";
   public static String field3034 = "Loading interfaces - ";
   public static String field3035 = "Loaded interfaces";
   public static String field3036 = "Loading world map - ";
   public static String field3037 = "Please enter your username/email address.";
   public static String field3038;
   public static String field3039 = "Discard";
   public static String field3040 = "Recover Account";
   public static String field3041 = "Connecting to update server";
   public static String field3042 = "Please enter a 6-digit PIN.";
   public static String field3043;
   public static String field3044 = "You have only just left another world.";
   public static String field3045 = "Your profile will be transferred in:";
   public static String field3046 = "in serious rule breaking.";
   public static String field3047 = "Connection timed out.";
   public static String field3048 = "Please try using a different world.";
   public static String field3049;
   public static String field3050 = "";
   public static String field3051 = "Please try using a different world.";
   public static String field3052 = "";
   public static String field3053 = "No response from server.";
   public static String field3054 = "Loading wordpack - ";
   public static String field3055;
   public static String field3056;
   public static String field3057;
   public static String field3058 = "";
   public static String field3059 = "Either your account is still logged in, or the last";
   public static String field3060 = "world you were using has become unavailable.";
   public static String field3061 = "Please try again later.";
   public static String field3062 = "RuneScape has been updated!";
   public static String field3063 = "Please reload this page.";
   public static String field3064;
   public static String field3065;
   public static String field3066 = "Please use a different world.";
   public static String field3067;
   public static String field3068 = "Unable to connect.";
   public static String field3069 = "Login server offline.";
   public static String field3070;
   public static String field3071 = "Login limit exceeded.";
   public static String field3072 = "Too many connections from your address.";
   public static String field3073;
   public static String field3074;
   public static String field3075 = "Bad session id.";
   public static String field3076 = "";
   public static String field3077 = "We suspect someone knows your password.";
   public static String field3078 = "Press 'change your password' on front page.";
   public static String field3079 = "Unable to connect.";
   public static String field3080 = "You need a members account to login to this world.";
   public static String field3081 = "Please subscribe, or use a different world.";
   public static String field3082 = "";
   public static String field3083 = "Could not complete login.";
   public static String field3084;
   public static String field3085 = "";
   public static String field3086 = "Please try using a different world.";
   public static String field3087 = "Please wait 1 minute and try again.";
   public static String field3088 = "";
   public static String field3089 = "Too many login attempts.";
   public static String field3090 = "You can use the Jagex Launcher to continue playing.";
   public static String field3091 = "The unpaid balance on your account needs";
   public static String field3092;
   public static String field3093 = "as it was used to break our rules.";
   public static String field3094 = "to a non-members area.";
   public static String field3095 = "Your account has been locked due to";
   public static String field3096 = "suspicious activity.";
   public static String field3097 = "Please recover your account.";
   public static String field3098 = "";
   public static String field3099 = "to be resolved before you can play.";
   public static String field3100 = "Please use a different world.";
   public static String field3101;
   public static String field3102 = "Please try using a different world.";
   public static String field3103;
   public static String field3104 = "Malformed login packet.";
   public static String field3105;
   public static String field3106 = "Your account has been involved";
   public static String field3107 = "No reply from loginserver.";
   public static String field3108 = "Please wait 1 minute and try again.";
   public static String field3109;
   public static String field3110 = "Error loading your profile.";
   public static String field3111 = "Please contact customer support.";
   public static String field3112;
   public static String field3113 = "Unexpected loginserver response.";
   public static String field3114 = "Please try using a different world.";
   public static String field3115 = "";
   public static String field3116 = "This computers address has been blocked";
   public static String field3117 = "View Appeal Options";
   public static String field3118 = "";
   public static String field3119;
   public static String field3120 = "Service unavailable.";
   public static String field3121 = "";
   public static String field3122 = "";
   public static String field3123;
   public static String field3124 = "";
   public static String field3125 = "";
   public static String field3126 = "Please enter your password.";
   public static String field3127 = "for 30 days: ";
   public static String field3128 = "";
   public static String field3129 = "in order to play the game.  Please set it";
   public static String field3130 = "via the website, or the main game.";
   public static String field3131 = "To access this free world, log into a";
   public static String field3132 = "Sorry invited players only.";
   public static String field3133;
   public static String field3134;
   public static String field3135 = "Loaded input handler";
   public static String field3136 = "Loaded world map";
   public static String field3137;
   public static String field3138;
   public static String field3139;
   public static String field3140;
   public static String field3141;
   public static String field3142 = "";
   public static String field3143;
   public static String field3144;
   public static String field3145;
   public static String field3146;
   public static String field3147;
   public static String field3148;
   public static String field3149;
   public static String field3150;
   public static String field3151;
   public static String field3152;
   public static String field3153;
   public static String field3154;
   public static String field3155;
   public static String field3157;
   public static String field3158 = "";
   public static String field3159;
   public static String field3160;
   public static String field3161 = "Please try using a different world.";
   public static String field3162;
   public static String field3163;
   public static String field3164 = "Take";
   public static String field3165;
   public static String field3166;
   public static String field3167;
   public static String field3168;
   public static String field3169;
   public static String field3170;
   public static String field3171 = "Please try again.";
   public static String field3172 = "";
   public static String field3173 = "Drop";
   public static String field3174;
   public static String field3175;
   public static String field3176;
   public static String field3177;
   public static String field3178;
   public static String field3179;
   public static String field3180;
   public static String field3181;
   public static String field3182;
   public static String field3183;
   public static String field3184;
   public static String field3185;
   public static String field3186;
   public static String field3187;
   public static String field3188;
   public static String field3189 = "This world is running a closed Beta.";
   public static String field3190 = "";
   public static String field3191;
   public static String field3192;
   public static String field3193 = "";
   public static String field3194;
   public static String field3195;
   public static String field3196;
   public static String field3197;
   public static String field3198;
   public static String field3199;
   public static String field3200;
   public static String field3201;
   public static String field3202;
   public static String field3203 = "Invalid loginserver requested.";
   public static String field3204;
   public static String field3205;
   public static String field3206;
   public static String field3207;
   public static String field3208;
   public static String field3209;
   public static String field3210 = "Error connecting to server.";
   public static String field3211;
   public static String field3212;
   public static String field3213 = "Loading fonts - ";
   public static String field3214;
   public static String field3215;
   public static String field3216;
   public static String field3217 = "";
   public static String field3218 = "Loaded config";
   public static String field3219 = "Press the button below to download it now.";
   public static String field3220 = "";
   public static String field3221;
   public static String field3222;
   public static String field3223;
   public static String field3224 = " seconds.";
   public static String field3225;
   public static String field3226;
   public static String field3227;
   public static String field3228;
   public static String field3229;
   public static String field3230 = " (Members)";
   public static String field3231;
   public static String field3232;
   public static String field3233;
   public static String field3234;
   public static String field3235;
   public static String field3236;
   public static String field3237;
   public static String field3238;
   public static String field3239;
   public static String field3240;
   public static String field3241;
   public static String field3242;
   public static String field3243 = "";
   public static String field3244;
   public static String field3245;
   public static String field3246;
   public static String field3247 = "members world and move your character";
   public static String field3248;
   public static String field3249;
   public static String field3250;
   public static String field3251;
   public static String field3252;
   public static String field3253 = "Hidden";
   public static String field3254;
   public static String field3255;
   public static String field3256;
   public static String field3257;
   public static String field3258;
   public static String field3259;
   public static String field3260;
   public static String field3261 = "Your account must have a displayname set";
   public static String field3262;
   public static String field3263;
   public static String field3264;
   public static String field3265;
   public static String field3266;
   public static String field3267;
   public static String field3268;
   public static String field3269;
   public static String field3270 = "";
   public static String field3271;
   public static String field3272;
   public static String field3273;
   public static String field3274;
   public static String field3275;
   public static String field3276 = "";
   public static String field3277;
   public static String field3278;
   public static String field3279;
   public static String field3280 = "The server is being updated.";
   public static String field3281;
   public static String field3282;
   public static String field3283 = "Select";
   public static String field3284;
   public static String field3285;
   public static String field3286;
   public static String field3287;
   public static String field3288;
   public static String field3289;
   public static String field3290;
   public static String field3291;
   public static String field3292;
   public static String field3293;
   public static String field3294;
   public static String field3295;
   public static String field3296;
   public static String field3297;
   public static String field3298;
   public static String field3299;
   public static String field3300;
   public static String field3301;
   public static String field3302;
   public static String field3303;
   public static String field3304;
   public static String field3305;
   public static String field3306;
   public static String field3307 = "Loaded textures";
   public static String field3308;
   public static String field3309;
   public static String field3310;
   public static String field3311 = "null";
   static String field3156 = "Please visit the support page for assistance.";

   static {
      field3133 = field3156;
      field3134 = "Your account is currently inaccessible.";
      field3163 = "Please try again in a few minutes.";
      field3278 = "";
      field3137 = "You need to vote to play!";
      field3138 = "Visit runescape.com and vote,";
      field3139 = "and then come back here!";
      field3140 = "Sorry, but your account is not eligible to play.";
      field3182 = "For more information, please take a look at";
      field3151 = "our privacy policy.";
      field3255 = "Privacy Policy";
      field3296 = "Enter the 6-digit code generated by your";
      field3009 = "authenticator app.";
      field3146 = "";
      field3147 = "The code you entered was incorrect.";
      field3148 = "Please try again.";
      field3149 = "";
      field3169 = "Login attempt timed out.";
      field3143 = "Please try again.";
      field3152 = "";
      field3153 = "You were signed out.";
      field3154 = "Please sign in again.";
      field3155 = "";
      field3207 = "Failed to login.";
      field3157 = "Please try again.";
      field3176 = "";
      field3159 = "Unexpected server response";
      field3021 = "Please try using a different world.";
      field3067 = "";
      field3162 = " has logged in.";
      field3056 = " has logged out.";
      field3145 = "Unable to find ";
      field3165 = "Use";
      field3166 = "Examine";
      field3167 = "Attack";
      field3168 = "Choose Option";
      field3032 = " more options";
      field3170 = "Walk here";
      field3011 = "level-";
      field3175 = "skill-";
      field3273 = "Please wait...";
      field3246 = "Close";
      field3049 = " ";
      field3070 = "M";
      field3177 = "M";
      field3178 = "K";
      field3179 = "K";
      field3180 = "World";
      field3181 = "Your friend list is full. Max of 200 for free users, and 400 for members";
      field3003 = " is already on your friend list";
      field3183 = "Your ignore list is full. Max of 100 for free users, and 400 for members";
      field3184 = " is already on your ignore list";
      field3185 = "You can't add yourself to your own friend list";
      field3186 = "You can't add yourself to your own ignore list";
      field3187 = "Please remove ";
      field3188 = " from your ignore list first";
      field3001 = "Please remove ";
      field3160 = " from your friend list first";
      field3101 = "yellow:";
      field3192 = "red:";
      field3103 = "green:";
      field3194 = "cyan:";
      field3073 = "purple:";
      field3196 = "white:";
      field3197 = "flash1:";
      field3008 = "flash2:";
      field3043 = "flash3:";
      field3065 = "glow1:";
      field3109 = "glow2:";
      field3202 = "glow3:";
      field3119 = "rainbow:";
      field3204 = "pattern";
      field3205 = "wave:";
      field3206 = "wave2:";
      field3055 = "shake:";
      field3208 = "scroll:";
      field3092 = "slide:";
      field3191 = "RuneScape is loading - please wait...";
      field3211 = "";
      field3212 = "Enter your username/email & password.";
      field3174 = "";
      field3030 = "Warning!";
      field3215 = "This is a <col=ff0000>PvP<col=ffffff> world.";
      field3216 = "Players can attack each other";
      field3017 = "almost everywhere.";
      field3306 = "This is a <col=ffff00>High Risk<col=ffffff> world.";
      field3240 = "The Protect Item prayer will";
      field3300 = "not work on this world.";
      field3221 = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
      field3222 = "Players can attack each other almost everywhere";
      field3223 = "and the Protect Item prayer won't work.";
      field3234 = "This is a <col=00ffff>Beta<col=ffffff> world.";
      field3225 = "Your normal account will not be affected.";
      field3226 = "";
      field3227 = "Authenticator";
      field3228 = "";
      field3229 = "Connecting to server...";
      field3214 = "";
      field3231 = "The game servers are currently being updated.";
      field3232 = "Please wait a few minutes and try again.";
      field3233 = "";
      field3248 = "";
      field3235 = "You were disconnected from the server.";
      field3236 = "";
      field3237 = "Login: ";
      field3238 = "Password: ";
      field3239 = "PIN: ";
      field3282 = "Welcome to RuneScape";
      field3241 = "New User";
      field3242 = "Existing User";
      field3198 = "Login";
      field3244 = "Cancel";
      field3245 = "Remember username";
      field3199 = "Hide username";
      field3252 = "Incorrect username or password.";
      field3064 = "If you have upgraded to a Jagex Account, you";
      field3249 = "need to log in using the <u=ffd200><col=ffd200>Jagex Launcher</col></u> instead.";
      field3250 = "Try again";
      field3251 = "Forgotten password?";
      field3201 = "Forgotten your password?";
      field3123 = "Username/email: ";
      field3254 = "Recover";
      field3294 = "Back";
      field3209 = "Can't login? Click here.";
      field3257 = "Still having trouble logging in?";
      field3258 = "Having trouble logging in?";
      field3259 = "";
      field3260 = "Page has opened in the browser.";
      field3144 = "";
      field3262 = "Please enter your username.";
      field3263 = "If you created your account after November";
      field3264 = "2010, this will be the creation email address.";
      field3265 = field3259;
      field3266 = field3260;
      field3267 = field3144;
      field3299 = "";
      field3269 = "Error connecting to server.";
      field3074 = "";
      field3271 = "The part of the website you are trying";
      field3272 = "to connect to is offline at the moment.";
      field3256 = "Please try again later.";
      field3274 = "Sorry, there was an error trying to";
      field3275 = "log you in to this part of the website.";
      field3268 = "Please try again later.";
      field3277 = "";
      field3038 = "Error connecting to server.";
      field3141 = "";
      field3006 = "You must enter a valid login to proceed. For accounts";
      field3281 = "created after 24th November 2010, please use your";
      field3105 = "email address. Otherwise please use your username.";
      field3279 = "Your date of birth isn't set.";
      field3284 = "Please verify your account status by";
      field3285 = "setting your date of birth.";
      field3286 = "Set Date of Birth";
      field3287 = "Your date of birth information is waiting";
      field3288 = "to be reviewed by our staff.";
      field3289 = "It will be processed shortly.";
      field3290 = "Before using this app, please read and accept our";
      field3291 = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
      field3292 = "<col=ffd200>agreement (EULA)</col>.";
      field3293 = "By accepting, you agree to these documents.";
      field3057 = "You must accept our terms of use, privacy policy,";
      field3295 = "and end user licence agreement to continue.";
      field3112 = "Accept";
      field3297 = "Decline";
      field3298 = "Select a world";
      field3026 = "Members only world";
      field3084 = "Free world";
      field3301 = "World";
      field3302 = "Players";
      field3303 = "Location";
      field3304 = "Type";
      field3305 = "OFF";
      field3200 = "FULL";
      field3150 = "Loading...";
      field3308 = "Click to switch";
      field3309 = "Download Launcher";
      field3310 = "https://oldschool.runescape.com/launcher";
      field3195 = "https://support.runescape.com/hc/en-gb/articles/360001552065";
   }

   class424() throws Throwable {
   }
}
